### PR TITLE
feat(all): adjusted package configurations, and added support for management via lerna lite

### PR DESCRIPTION
**Pull request by z3dev**
Given that there are many sub-packages, I suggest moving to lerna lite for managing each of the packages, which should make it easy to build, and test later.

As a bonus, there's a new package.json for dissection which has several scripts to setup / cleanup linkages to the other sub-packages, and start 'dev' webserver.

### CODE REVIEW

**Comment by daef** [comment]
I've never heard about lerna. I should probably read up on that a bit :)

**Comment by daef** [comment]
I like what I see about lerna, trying to ./run I first had to change `--export-png` to `--export-filename` for current inkscape, but it still fails pretty hard.

**Comment by z3dev** [comment]
> I like what I see about lerna, trying to ./run I first had to change `--export-png` to `--export-filename` for current inkscape, but it still fails pretty hard.

Yeah. I have that change as well. The current Inkscape is very different on the command line. 

These changes are focused on the initial setup of each sub-project. Although, I couldn't determine how to set up some of the packages, like the RUST library.

We can add more scripts to do almost anything across the packages. I will add a few in another pull request. I hope that @platypul also likes this direction.

**Comment by z3dev** [comment]
@daef What do you think? Anything that should be changed?

**Comment by daef** [comment]
is it already running though? o0

**Comment by z3dev** [comment]
Sure. Here's the output of running 'npm run setup'

```
npm run setup

> poly-bool-comparison@1.0.0 setup
> lerna run setup

lerna-lite notice cli v1.14.1
lerna-lite info Executing command in 4 packages: "npm run setup"
lerna-lite info run Ran npm script 'setup' in 'pathkit' in 0.6s:

> pathkit@1.0.0 setup
> npm install


up to date, audited 2 packages in 237ms

found 0 vulnerabilities
lerna-lite info run Ran npm script 'setup' in 'voidqk' in 0.6s:

> voidqk@1.0.0 setup
> npm install


up to date, audited 2 packages in 237ms

found 0 vulnerabilities
lerna-lite info run Ran npm script 'setup' in 'dissection' in 0.6s:

> dissection@1.0.0 setup
> npm install && npm run create-links


up to date, audited 1 package in 37ms

found 0 vulnerabilities

> dissection@1.0.0 create-links
> ln -sf ../magick && ln -sf ../martinez_cgal && ln -sf ../martinez_cpp && ln -sf ../milevski && ln -sf ../pathkit && ln -sf ../rust-geo-booleanop && ln -sf ../unisamples && ln -sf ../voidqk

lerna-lite info run Ran npm script 'setup' in 'milevski' in 0.9s:

> milevski@1.0.0 setup
> npm install


up to date, audited 5 packages in 556ms

found 0 vulnerabilities
lerna-lite success run Ran npm script 'setup' in 4 packages in 1.0s:
lerna-lite success - dissection
lerna-lite success - milevski
lerna-lite success - pathkit
lerna-lite success - voidqk
npm notice 
npm notice New minor version of npm available! 9.5.0 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 

```

**Comment by z3dev** [comment]
If you can provide information on how to install these packages/apps then I can add to the setup as well.

- magick
- martinez_cgal
- martinez_cpp

**Comment by daef** [comment]
oh, then i guess i'll have to try this :)

**Comment by z3dev** [comment]
@daef please try.

I updated the README to include the steps in the installation process. It's actually very simple now.

**Comment by daef** [comment]
I'm on a trip. I'll be back in a week! Looking forward to :)

**Comment by daef** [comment]
sorry, the whole family was sick - cloning your branch right now

**Comment by daef** [comment]
seems to run through just nice after a few small changes. I'll merge it and push my changes on top :)

**Pull request merged**
